# Generated by Django 4.1.4 on 2023-02-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Student',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
